### ISSUE TITLE
~2 year old terraform version required?

### ISSUE THREAD

**Issue by anderiv** [santrancisco/relaysecret#4]
backend.tf seems to require terraform version 0.13.2, which was released nearly 2 years ago. Is this intentional? Can a newer terraform version be used successfully? Thank you!

**Comment by santrancisco** [comment]
Thanks for pointing this out @anderiv  it is THAT long since I last making changes to relaysecret backend and it's been humming away with no issue. I have [updated it now ](https://github.com/santrancisco/relaysecret/pull/5) so you should not have any problem with applying it to your own AWS account..
